### ISSUE TITLE
soften yajl-ruby version requirement or bump version

### ISSUE THREAD

**Issue by fbjork** [flaptor/indextank-rb#2]
We're using yajl-ruby 0.7.9 in our app, any chance you could bump the version requirement or soften the version check to minor instead of tiny?

**Comment by iladriano** [comment]
Yes, we can do it.

**Comment by iladriano** [comment]
Pushed indextank-1.0.7 to rubygems.

**Comment by fbjork** [comment]
Thanks! Amazingly fast response.
