### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by corasaurus-hex** [flaptor/indextank-rb#4]
Tests are broken with an error of "Can't convert Array into String". Tried locking at precisely the same versions of gems listed in the Gemfile to no avail. I even tried pre 0.6.0 faraday versions.

**Comment by dbuthay** [comment]
Thanks for the report. I fixed the tests on version 1.0.9. It uses faraday 0.6.0 now.
I haven't uploaded the gem yet.
